CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255) NOT NULL,
    email   VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists ITEMS
(
    ITEM_ID          BIGINT auto_increment,
    ITEM_NAME        CHARACTER VARYING(64) not null,
    ITEM_DESCRIPTION CHARACTER VARYING(1000) not null,
    ITEM_AVAILABLE   BOOLEAN   not null,
    ITEM_OWNER_ID    BIGINT    not null,
    constraint ITEMS_ITEM_ID_PK
        primary key (ITEM_ID),
    constraint ITEMS_USERS_USER_ID_FK
        foreign key (ITEM_OWNER_ID) references USERS on delete cascade
);
